image:
  repository: quarkus
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "myversion"
replicaCount: 1  