image:
  repository: host.docker.internal:30050/quarkus
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.269"
replicaCount: 1  